### ISSUE TITLE
Need a method to run scripts inside running pods/containers

### ISSUE THREAD

**Issue by Eagerod** [Eagerod/hope#28]
Hope currently doesn't have a way of running scripts inside existing pods. This can be a problem when scripts need to be running alongside processes that are already running. 

This could be done as an `exec` style deployment type, which lists out a selector of pods it can run against, and a single command that can be run against it.

ex:

```
  - name: do-some-thing
    exec:
      selector:
        app: something-cool
      command: /bin/sh -c "cp /some/file /somewhere/else && echo 'I did a thing'"
```

The tool could wait some reasonable amount of time for a pod with the given selector to be ready, and once it's ready, run the script.
